default: &default
  store: :redis_cache_store
  options:
    url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/0") %>
    namespace: <%= Rails.env %>
    reconnect_attempts: 1
    error_handler: -> (method:, returning:, exception:) {
      Rails.logger.error("Redis cache error: #{exception.class}: #{exception.message}")
    }

development:
  <<: *default

test:
  store: :memory_store

production:
  <<: *default
