default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "coder") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

development:
  <<: *default
  database: issued_development

test:
  <<: *default
  database: issued_test

production:
  primary:
    <<: *default
    database: issued_production
  queue:
    <<: *default
    database: issued_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: issued_production_cable
    migrations_paths: db/cable_migrate
